- name: multi playbook play-1
  hosts:  localhost
  become: yes
  tasks:
    - name: play1 & task 1
      ansible.builtin.debug:
        msg: hi this from play1&task1

- name: playbook play2
  hosts: localhost
  become: yes
  tasks:
    - name: play2 & task2
      ansible.builtin.debug:
        msg: this is from play2 & task2